### PR TITLE
Auth tests

### PR DESCRIPTION
**Pull request by dsgoers**

### CODE REVIEW

**Comment by dsgoers** [comment]
by public, do you mean the endpoint doesn't require authorization?

**Comment by soberstadt** [comment]
Yes, that is what I meant

**Comment by dsgoers** [comment]
Yes, there's a lot of public endpoints.

**Comment by dsgoers** [comment]
I see what you're saying... maybe later I'll add that.  For now the most important thing is making sure secured endpoints are actually secure.

**Pull request merged**
