### PR TITLE
Upgrade to Rails 5.2.3

### PR DESCRIPTION
**Pull request by jbirdjavi**

### CODE REVIEW

**Comment by jbirdjavi** [comment]
Successfully deployed to staging.

**Comment by frett** [comment]
I'm getting 422 errors whenever I try to access the protected APIs.

rollbar error: https://rollbar.com/Cru/mobile-content-api/items/142/

**Comment by jbirdjavi** [comment]
@frett I believe they should be working now.

**Comment by frett** [comment]
@jbirdjavi looks good now, you still need to move that commit to this branch from staging

**Pull request merged**
