### PR TITLE
GT-775, implement storing dynamic attributes for resources

### PR DESCRIPTION
**Pull request by andrewroth**

### CODE REVIEW

**Comment by frett** [comment]
This currently works for setting new attributes, but doesn't appear to work for updating or deleting existing attributes.

The following request:
```
PUT https://mobile-content-api-stage.cru.org/resources/12
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": {
        "type": "resource",
        "attributes": {
            "attr-testIntB": 2
        }
    }
}
```

returns the following error:
```
{
    "errors": [
        {
            "source": {
                "pointer": "/data/attributes/id"
            },
            "detail": "Validation failed: Resource has already been taken"
        }
    ]
}
```

**Comment by frett** [comment]
also, when the update endpoint succeeds it returns `true` instead of the updated resource object in the JSONAPI format

**Review by frett — APPROVED** [review]
From a functional standpoint everything looks good

**Comment by frett** [comment]
@andrewroth this is good to merge unless you have any other concerns about it

**Comment by andrewroth** [comment]
Goof from my end

**Pull request merged**
