### PR TITLE
upgrade sprockets

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by dsgoers** [comment]
What's the reason for the upgrade?

**Comment by frett** [comment]
Fixes a CVE

**Comment by frett** [comment]
I encountered it with this PR: https://github.com/CruGlobal/mobile-content-api/pull/153

**Comment by frett** [comment]
it's been running on staging for a couple days :) I'm working on some admin tool improvements as well as scoping out a bit of work to better support showing tracts on the web.

**Pull request merged**
