### PR TITLE
Upgrade to Rails 7

### PR DESCRIPTION
**Pull request by jbirdjavi**
I took out any asset/javascript stuff since it doesn't seem to be used, and it's not in the Rails core stuff anymore.

### CODE REVIEW

**Comment by jbirdjavi** [comment]
@frett Feel free to push to staging at your leisure to make sure it's working fine.

**Comment by frett** [comment]
K, i'll probably try it out tomorrow morning if I have a chance

**Review by frett — APPROVED** [review]
Everything appears to be working on stage, so this is good to push to production. We should probably wait until Monday to actually push it to production

**Comment by jbirdjavi** [comment]
Great! Maybe the following Monday, since I'll be out for RailsConf next week.

**Comment by frett** [comment]
cool, I'm good with waiting until you are back that way you're around in case something does go awry

**Comment by jbirdjavi** [comment]
@frett Thanks for the reminder. I'll push this in about 15 minutes.

**Pull request merged**
