### PR TITLE
Image scale type and align

### PR DESCRIPTION
**Pull request by frett**
sample xml:

```xml
<manifest
    background-image="image.png"
    background-image-align="bottom start"
    background-image-scale-type="fit" />
```
```xml
<page
    background-image="image.png"
    background-image-align="bottom"
    background-image-scale-type="fill-x" />
```
```xml
<card
    background-image="image.png"
    background-image-align="center"
    background-image-scale-type="fill-x" />
```

### CODE REVIEW

**Comment by frett** [comment]
@pablomarti here is the updated attributes and values for them.

**Comment by pablomarti** [comment]
I saw the changes and are good for me @frett, is this the final? (last change was 26mins ago)

**Comment by frett** [comment]
I had missed including the attributes on the page itself. The xml is final, I might do some XML schema cleanup down the line, but for now this PR is done.

**Comment by frett** [comment]
and I need to resolve conflicts before I merge :)

**Pull request merged**
