### PR TITLE
Gt 449 right to left attribute

### PR DESCRIPTION
**Pull request by ryancarlson**
Adds "direction" attribute to language. This attribute will help clients know which way text ought to be rendered for a given languages. Defaults to "ltr" unless otherwise specified.

endpoint validates values to be either: "ltr" and "rtl"

### CODE REVIEW

**Comment by ryancarlson** [comment]
cc @frett

**Comment by ryancarlson** [comment]
@sheldond Here's a PR that introduces a "direction" attribute on languages served by the mobile-content-api. i mentioned we might do this in our call for knowgod.com. Another use-case came up yesterday for the iOS client, so I went ahead with introducing it.

**Comment by sheldond** [comment]
@ryancarlson Perfect, thanks for the update!

**Comment by ryancarlson** [comment]
thanks for reviewing @knutsenm ! thanks for your input @dsgoers and others

**Pull request merged**
